### ISSUE TITLE
Bug unbound variable in copy_admin_scripts.sh

### ISSUE THREAD

**Issue by mahdihasnat** [rebornplusplus/contest-iso#10]
```bash
source vars.sh

cd $ADMIN_SCRIPTS_DIR

homedir="/home/$ADMIN_USER"
for file in *; do
	cp -rv $file "$homedir/"
	chown -R -c -v $user:$user "$homedir/$file"
	chmod -R -v 750 "$homedir/$file"
done

cd -
```
Here `$user` is unbound variable. Should it be `$ADMIN_USER`?

**Comment by rebornplusplus** [comment]
Seems like it. We should probably run `shellcheck` in our CI from now on, now that the project has a shape.

**Comment by mahdihasnat** [comment]
I am going to add a pr to fix this file only, will take a look to integrate `shellcheck`.
